export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_FILM_PENDING = 'REQUEST_FILM_PENDING';
export const REQUEST_FILM_SUCCESS = 'REQUEST_FILM_SUCCESS';
export const REQUEST_FILM_FAILED = 'REQUEST_FILM_FAILED';
